### PR TITLE
rfc(0041): rfc of Naming Convention for Nervos Cross-Chain Assets.

### PR DESCRIPTION
**Pull request by Daryl-L**

### CODE REVIEW

**Comment by doitian** [comment]
RFC# 41 (see https://github.com/nervosnetwork/rfcs/issues/246)

**Comment by doitian** [comment]
Hey, for new RFC, please check the process in README

> ### Discuss Your Idea with Community
>
> Before submitting a RFC pull request, you should send the draft to community to solicit initial feedbacks. The [\#rfc-chat discord channel](https://discord.gg/SWE7AtDKc4) or [Nervos Talk](https://talk.nervos.org/) are both good places to go.

**Comment by janx** [comment]
Thanks for putting things together and kick the documentation process off @Daryl-L . I'll create a more comprehensive draft and close this one.

**Comment by janx** [comment]
> Hey, for new RFC, please check the process in README
> 
> > ### Discuss Your Idea with Community
> > Before submitting a RFC pull request, you should send the draft to community to solicit initial feedbacks. The [#rfc-chat discord channel](https://discord.gg/SWE7AtDKc4) or [Nervos Talk](https://talk.nervos.org/) are both good places to go.

This is a conversion of previous work by me and Wenchao Hu , a description of the naming convention used in forcebridge, godwoken and godwoken dapps. The idea is to document these conventions so dapp developers can better understand the naming rules and build compatible UX. In this case maybe we can begin with a PR and skip Nervos talk post?

**Pull request closed without merging**
